// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp9c3yRqWS-CZBEMaI-lkovcqnylNuXGk',
    appId: '1:435543273224:web:2c529c3c1a3e7a5d4cc6bd',
    messagingSenderId: '435543273224',
    projectId: 'allevents-a0ea2',
    authDomain: 'allevents-a0ea2.firebaseapp.com',
    storageBucket: 'allevents-a0ea2.appspot.com',
    measurementId: 'G-GPPPKDLNK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVqspbB1UXZpAP0gu8zwyf88-o_Vn1pE',
    appId: '1:435543273224:android:d8aa35acdb56a55e4cc6bd',
    messagingSenderId: '435543273224',
    projectId: 'allevents-a0ea2',
    storageBucket: 'allevents-a0ea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_il4LGF6gnoYmvmkZJXd2pa0NaCx9IU',
    appId: '1:435543273224:ios:a0fa7a807f97cecf4cc6bd',
    messagingSenderId: '435543273224',
    projectId: 'allevents-a0ea2',
    storageBucket: 'allevents-a0ea2.appspot.com',
    iosBundleId: 'com.example.allEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW_il4LGF6gnoYmvmkZJXd2pa0NaCx9IU',
    appId: '1:435543273224:ios:44098edec6fdd4544cc6bd',
    messagingSenderId: '435543273224',
    projectId: 'allevents-a0ea2',
    storageBucket: 'allevents-a0ea2.appspot.com',
    iosBundleId: 'com.example.allEvents.RunnerTests',
  );
}
